// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }
//
//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAdc-S6OD2fe7bT0uLW2wUrSZ9jkTTXNkQ',
//     appId: '1:1095321595178:android:1ce0a502c848db57118253',
//     messagingSenderId: '1095321595178',
//     projectId: 'receipt-generator-7c33b',
//     storageBucket: 'receipt-generator-7c33b.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDXNQOOqTue_3tMiaT-j8fXH_YHAbmS_1A',
//     appId: '1:1095321595178:ios:062261152837f843118253',
//     messagingSenderId: '1095321595178',
//     projectId: 'receipt-generator-7c33b',
//     storageBucket: 'receipt-generator-7c33b.appspot.com',
//     iosClientId: '1095321595178-o6cbl7gmi6v1f7pjvntk50dmm3d8bh31.apps.googleusercontent.com',
//     iosBundleId: 'com.nearbai.xpos',
//   );
// }
